MERGE INTO appointment VALUES
  (1, CURRENT_DATE(), 1, 0, FALSE, FALSE);

ALTER SEQUENCE appointment_seq RESTART WITH 2;
ALTER SEQUENCE seq_TP RESTART WITH 4;
ALTER SEQUENCE seq_TS RESTART WITH 5;
ALTER SEQUENCE seq_ES RESTART WITH 58;